-- Core geo schema. Column types/lengths/nullability mirror the JPA entities

CREATE TABLE geo_units (
    code                  VARCHAR(8)              NOT NULL,
    name                  VARCHAR(255)            NOT NULL,
    geometry              geometry(Geometry, 4326),
    geometry_3763         geometry(Geometry, 3763),
    area_ha               double precision,
    perimeter_km          double precision,
    type                  integer                 NOT NULL,
    parent_code           VARCHAR(8),
    simplified_name       VARCHAR(255),
    nuts1_code            VARCHAR(4),
    nuts3_code            VARCHAR(5),
    representative_point  geometry(Point, 4326),
    administrative_center geometry(Point, 4326),
    municipality_count    integer,
    parish_count          integer,
    coastline_km          double precision,
    CONSTRAINT geo_units_pkey PRIMARY KEY (code),
    CONSTRAINT fk_geo_units_parent FOREIGN KEY (parent_code) REFERENCES geo_units (code)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE geo_unit_precisions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    geo_unit_code VARCHAR(8)               NOT NULL,
    type          integer                  NOT NULL,
    lod           integer                  NOT NULL,
    geometry      geometry(Geometry, 4326) NOT NULL,
    tolerance_m   double precision,
    vertex_count  integer,
    generation_id uuid,
    created_at    timestamp(6) with time zone,
    CONSTRAINT geo_unit_precisions_pkey PRIMARY KEY (id)
);

CREATE TABLE border_segments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    geometry            geometry(Geometry, 4326),
    geometry_3763       geometry(Geometry, 3763),
    level               integer,
    line_type           VARCHAR(10),
    ea_right            VARCHAR(8),
    ea_left             VARCHAR(8),
    pais                VARCHAR(100),
    estado_limite_admin VARCHAR(100),
    length_km           double precision,
    CONSTRAINT border_segments_pkey PRIMARY KEY (id)
);

CREATE TABLE border_segment_precisions (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    border_segment_id bigint                   NOT NULL,
    level             integer,
    line_type         VARCHAR(10),
    length_km         double precision,
    lod               integer                  NOT NULL,
    geometry          geometry(Geometry, 4326) NOT NULL,
    tolerance_m       double precision,
    vertex_count      integer,
    generation_id     uuid,
    created_at        timestamp(6) with time zone,
    CONSTRAINT border_segment_precisions_pkey PRIMARY KEY (id)
);

CREATE TABLE precision_generations (
    generation_id      uuid        NOT NULL,
    created_at         timestamp(6) with time zone,
    status             VARCHAR(20) NOT NULL,
    total_units        integer,
    total_lods         integer,
    invalid_geometries integer,
    null_geometries    integer,
    row_count          integer,
    CONSTRAINT precision_generations_pkey PRIMARY KEY (generation_id)
);

CREATE TABLE geo_unit_adjacency (
    code           VARCHAR(8) NOT NULL,
    neighbour_code VARCHAR(8) NOT NULL,
    CONSTRAINT geo_unit_adjacency_pkey PRIMARY KEY (code, neighbour_code)
);
