services:
  postgres:
    build: .
    image: terrapi-postgis-pgrouting:18-3.6
    container_name: terrapi-db
    command:
      - postgres
      - -c
      - maintenance_work_mem=2GB
      - -c
      - max_wal_size=4GB
      - -c
      - synchronous_commit=off
    environment:
      POSTGRES_DB: terrapi
      POSTGRES_USER: terrapi
      POSTGRES_PASSWORD: terrapi
    ports:
      - "5445:5432"
    volumes:
      - pgdata:/var/lib/postgresql/

volumes:
  pgdata:
